config/routes.rb
TapTracker::Application.routes.draw do
  resources :users
  resources :kegs
  resources :pours

  root "pours#new"
end

app/models/keg.rb
class Keg < ActiveRecord::Base
  has_many :pours
  validates :name, presence: true
  after_initialize :init

  def init
    self.volume ||= 0.0
  end

  def self.current_kegs
    where(currently_tapped: true)
  end 

  def volume_in_gallons
    (volume || 0) / 128
  end

  def volume_remaining
    volume - total_poured
  end

  def pours_remaining
    volume_remaining / 12
  end

  def total_poured
    pours.map(&:volume).reduce(0, :+)
  end
end

app/models/pour.rb
class Pour < ActiveRecord::Base
  belongs_to :keg
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pours
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/kegs_controller.rb
class KegsController < ApplicationController

  def new
  end

  def create
    @keg = Keg.new(keg_params)
    @keg.save
    redirect_to @keg
  end

  def show
    @keg = Keg.find(params[:id])
  end

  def index
    @kegs = Keg.all
  end

  def edit
    @keg = Keg.find(params[:id])
  end

  def update
    @keg = Keg.find_by(id: params[:id])
    @keg.update(keg_params)
    redirect_to @keg
  end

  private
  
  def keg_params
    params.require(:keg).permit(:name, :currently_tapped, :volume)
  end

end

app/controllers/pours_controller.rb
class PoursController < ApplicationController
  
  def new
    @keg
  end

  def create
    @pour = Pour.new(pour_params)
    @pour.save
    redirect_to @pour.user
  end

  def show
    @pour = Pour.find(params[:id])
  end

  private

  def pour_params 
    params.require(:pour).permit(:volume, :keg_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to @user    
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:danger, :info, :success, :warning] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert || type == :error
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kegs/edit.haml
%h1 Edit Keg
= form_for :keg, url: keg_path(@keg), method: :put do |f| 
  %p
    = f.label "Keg Name:"
    = f.text_field :name, value: @keg.name
    = f.label "Currently tapped?"
    = f.check_box :currently_tapped

  %p
    = f.submit 

  %p
    = link_to 'Back to Drinking', new_pour_path

app/views/kegs/index.haml
%h1 Available Kegs
 
%table
  %th Name:
  - @kegs.each do |keg|
    %tr
      %td= keg.name
      %td= "#{keg.volume_in_gallons} Gallons"
      %td= link_to 'Edit', edit_keg_path(keg)

app/views/kegs/new.haml
%h1 Create New Keg
= form_for :keg, url: kegs_path do |f| 
  %p
    = f.label "Keg Name:"
    = f.text_field :name, value: @keg.try(:name)
    = f.label "Currently tapped?"
    = f.check_box :currently_tapped
    = f.label "Keg Size"
    = f.select(:volume, options_for_select([["5 gallon", 640], ["15.5 gallons", 1984]], "5 gallon"))

  %p
    = f.submit 

  %p
    = link_to 'Back to Drinking', new_pour_path

app/views/kegs/show.haml
%p
  %strong Name:
  = @keg.name

%p
  = link_to 'Back to Drinking', new_pour_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Darwinfe" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <%= bootstrap_flash %>
        <%= yield %>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
</html>

app/views/pours/new.haml
.row
  .col-xs-6
    %h1 Create New Pour
    = form_for :pour, url: pours_path do |f|

      %p
        = f.label "User Name"
        = collection_select(:pour, :user_id, User.all, :id, :username, {:prompt => 'Pick a user'})

      %p
        =f.label "Kegs"
        = collection_select(:pour, :keg_id, Keg.all, :id, :name)

      
      %p
        = f.label "Volume: "
        = f.select(:volume, options_for_select([[8, 8], [12, 12], [16, 16]], 12)) 

      %p
        = f.submit
        = link_to 'New User', new_user_path
        = link_to 'Add Keg', new_keg_path


  .col-xs-6
    %table.table.table-condensed.table-hover.narrow-gutter
      %td 
        %h2 Keg name
      %td 
        %h2 Pours Left
      - Keg.current_kegs.each do |k| 
        %tr 
          %td= "#{k.name}"
          %td= "#{k.pours_remaining}"

app/views/pours/show.html.erb
<p>
  <strong>Username: </strong>
  <%= @pour.user.username %> <br>
  <strong>Volume:</strong>
  <%= @pour.volume %> <br>
  <strong>Keg: </strong>
  <%= @pour.keg.name %>
</p>

app/views/users/index.html.erb
<h1>Listing Usernames</h1>
 
<table>
  <tr>
    <th>Username: </th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.haml
%h1 Create New Drinker
= form_for :user, url: users_path do |f|
  %p
    = f.label "Drinker:"
    = f.text_field :username 

  %p
    = f.submit 'New Drinker' 
    = link_to 'Back to Drinking', new_pour_path

app/views/users/show.haml
.row
  %strong Username: 
  = @user.username

%h2
  Pours:
%table.table.table-condensed.table-hover.narrow-gutter
  %td
    %strong Index
  %td
    %strong Keg name
  %td
    %strong Date
  %td
    %strong Volume in ounces

  - @user.pours.reverse.each_with_index do |pour, index|
    %tr
      %td= "#{index + 1}"
      %td= "#{pour.keg.try :name}"
      %td= "#{pour.created_at.to_formatted_s(:short)}"
      %td= "#{pour.volume}"

%p
  = link_to 'Back to drikning', new_pour_path